/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventdrivenchristmasgifts;


import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * EventDrivenChristmasGifts.java
 * john
 * 28th/11/2020
 */

public class EventDrivenChristmasGifts extends javax.swing.JFrame 
{
    ArrayList<ChristmasIdeas> giftIdeas = new ArrayList<ChristmasIdeas>();
     //ChristmasIdeas[] giftIdeas;
          
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventDrivenChristmasGifts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventDrivenChristmasGifts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventDrivenChristmasGifts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventDrivenChristmasGifts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventDrivenChristmasGifts().setVisible(true);
            }
        });
    }
    /**
     * Creates new form eventdrivenchristmasgifts
     */
    public EventDrivenChristmasGifts()
    {
        initComponents();
        //Set JFrame to center//
        this.setLocationRelativeTo(null);
    }

    //Clear textfield data//
    private void clearTextfields()
    {
        recipientNameTextField.setText("");
        giftIdeaTextField.setText("");
        urlTextField.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        displayGiftIdeasBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        recipientNameTextField = new javax.swing.JTextField();
        giftIdeaTextField = new javax.swing.JTextField();
        urlTextField = new javax.swing.JTextField();
        lblRecipientNameTitle = new javax.swing.JLabel();
        lblGiftIdeaTitle = new javax.swing.JLabel();
        lblURLTitle = new javax.swing.JLabel();
        addGiftIdeaBTN = new javax.swing.JButton();
        deleteGiftIdeaBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Christmas Gift Idea App");
        setResizable(false);

        displayGiftIdeasBTN.setText("Display Gift Ideas");
        displayGiftIdeasBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayGiftIdeasBTNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Christmas Gift Ideas");
        jLabel1.setToolTipText("");

        lblRecipientNameTitle.setText("Recipient Name:");

        lblGiftIdeaTitle.setText("Gift Idea:");

        lblURLTitle.setText("URL:");

        addGiftIdeaBTN.setText("Add Gift Idea");
        addGiftIdeaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGiftIdeaBTNActionPerformed(evt);
            }
        });

        deleteGiftIdeaBTN.setText("Delete Gift Idea");
        deleteGiftIdeaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGiftIdeaBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addGiftIdeaBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(deleteGiftIdeaBTN))
                                    .addComponent(displayGiftIdeasBTN)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRecipientNameTitle)
                                    .addComponent(lblGiftIdeaTitle)
                                    .addComponent(lblURLTitle))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(urlTextField)
                                    .addComponent(giftIdeaTextField)
                                    .addComponent(recipientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recipientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRecipientNameTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giftIdeaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGiftIdeaTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblURLTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addGiftIdeaBTN)
                    .addComponent(displayGiftIdeasBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteGiftIdeaBTN)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Event to add gift to giftIdeas arrayList//
    private void addGiftIdeaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGiftIdeaBTNActionPerformed
        //BOOL: check if the name is already in the arrayList
        boolean isNameFound = giftIdeas.stream().anyMatch(e -> e.getName().contains(recipientNameTextField.getText()));  
        //If textfield is empty//    
        if (recipientNameTextField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Error:\nTextfield is empty.", "Error: Empty field", JOptionPane.ERROR_MESSAGE);
        }
        //ELSE IF: gift ideas contain the textfield input is true//
        else if (isNameFound) 
        {
            JOptionPane.showMessageDialog(null, "Error:\nName is already entered.", "Error: Name", JOptionPane.ERROR_MESSAGE);
        }
        //ELSE IF: gift ideas contain the textfield input is false//
        else if (!isNameFound) 
        {
            //Add values to giftIdeas//
            giftIdeas.add(new ChristmasIdeas(recipientNameTextField.getText(), giftIdeaTextField.getText(), urlTextField.getText()));
            //Display to the user that it was added//
            JOptionPane.showMessageDialog(null, "Succesful added! \nName:" + recipientNameTextField.getText() + "\nGift: " + giftIdeaTextField.getText() + "\nURL: " + urlTextField.getText(), "Succesfully added!", HEIGHT);
            //Clear all textfields//
            clearTextfields();
        }        
    }//GEN-LAST:event_addGiftIdeaBTNActionPerformed
    //Even to display giftIdeas//
    private void displayGiftIdeasBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayGiftIdeasBTNActionPerformed
       if (giftIdeas.isEmpty())
       {
            JOptionPane.showMessageDialog(null, "Please add data", "Error, no items in list", JOptionPane.ERROR_MESSAGE);
       }
       else
       {
           JOptionPane.showMessageDialog(null, "List" + giftIdeas.toString()  , "Christmas Gifts", JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_displayGiftIdeasBTNActionPerformed
    //Event to delete giftIdea by name//
    private void deleteGiftIdeaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGiftIdeaBTNActionPerformed
        //String to temp' store the name//
        String searchedName = JOptionPane.showInputDialog(null, "Enter the name to delete the gift");
        //Boolean to true/false if giftIdeas match searchedName//
       // boolean found = giftIdeas.stream().anyMatch(e -> e.getName().contains(searchedName)); 
        boolean found = giftIdeas.stream().anyMatch(e -> e.getName().contains(searchedName)); 
        /*
        IF: name is found, loop through the list and proceed to delete the item
        */
        if (found == true)
        {  
            for (int i = giftIdeas.size() - 1; i >= 0; i--)
            {
                if (giftIdeas.get(i).getName().matches(searchedName))
                {
                    giftIdeas.remove(i);
                   
                }
            }   
            JOptionPane.showMessageDialog(null, "The name you have entered, their gift was removed", "Gift Idea Removed", JOptionPane.INFORMATION_MESSAGE);
        }
        /*
        ELSE IF: show that the value entered was not found in the array
        */
        else
        {
           JOptionPane.showMessageDialog(null, "Name was not found", "Not Found", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteGiftIdeaBTNActionPerformed


    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGiftIdeaBTN;
    private javax.swing.JButton deleteGiftIdeaBTN;
    private javax.swing.JButton displayGiftIdeasBTN;
    private javax.swing.JTextField giftIdeaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGiftIdeaTitle;
    private javax.swing.JLabel lblRecipientNameTitle;
    private javax.swing.JLabel lblURLTitle;
    private javax.swing.JTextField recipientNameTextField;
    private javax.swing.JTextField urlTextField;
    // End of variables declaration//GEN-END:variables













}
